name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run check
      run: make kong-postgres-kafka

    - name: Check api gateway
      run: curl -i -X GET 127.0.0.1:8001
